Who is Mattias
- Lives in Stockholm
- Have 2 kids
- Loves skiing
- Been working as a ski instructor
- really good at brewing beer
- Born and raised in Malmö
- Move to Stockholm 10 years ago
- Favorite movie is Lord of the rings, but Everything everwhere all at once is a great challenger
- Favorite book is Hitchhikers guide of the galaxy
- Favorite song is Dead of night by Orville Peck
- I have a dream running a taco truck/waggon as a side business
